-- USE DATABASE
USE alx_book_store;

-- FULL DESCRIPTION OF BOOKS TABLE WITHOUT DESCRIBE OR EXPLAIN
SELECT
    COLUMN_NAME,
    COLUMN_TYPE,
    IS_NULLABLE,
    COLUMN_KEY,
    COLUMN_DEFAULT,
    EXTRA
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'alx_book_store'
AND TABLE_NAME = 'Books';
